name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display repository info
        run: echo "Repository: ${{ github.repository }}"

      - name: Run a simple command
        run: echo "CI Workflow is running!"

