name: GitHub Actions Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print GitHub Event Details
        run: |
          echo "Triggered by ${{ github.event_name }}"
          echo "Running on ${{ runner.os }}"

      - name: List Repository Files
        run: ls ${{ github.workspace }}

      - name: Job Completion
        run: echo "CI/CD job completed successfully."

